# index.py
import os
import asyncio
import logging
from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse, PlainTextResponse
from fastapi.encoders import jsonable_encoder
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from crew.crew import run_pipeline

# --- Load environment variables ---
load_dotenv()

# --- Logging setup ---
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("FinanceCrewAI")

# --- Initialize app ---
app = FastAPI(
    title="Finance CrewAI API",
    version="1.0.2",
    description="AI-powered financial research API using CrewAI and Mistral-7B via OpenRouter."
)

# --- Enable CORS (for web frontends or Streamlit dashboard) ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def root():
    return {
        "message": "🚀 Finance CrewAI API is live!",
        "example_usage": "/api/report?ticker=AAPL&period=1mo",
        "health_check": "/api/health"
    }

@app.get("/api/health")
def health():
    return {"status": "ok"}

@app.get("/api/report")
async def report(
    ticker: str = Query("AAPL", description="Ticker symbol, e.g. AAPL or INFY.NS"),
    period: str = Query("1mo", description="Time period, e.g. 1mo, 3mo, 6mo"),
    format: str = Query("json", description="Output format: json or md"),
):
    """
    Runs the AI-powered Crew pipeline for financial analysis.
    Returns a structured JSON report or markdown summary.
    """
    try:
        logger.info(f"Running pipeline for {ticker} ({period})")

        # Run sync pipeline in background thread so FastAPI event loop is non-blocking
        result = await asyncio.to_thread(run_pipeline, ticker, period)

        if not result:
            logger.warning("Pipeline returned no result.")
            return JSONResponse(
                {"error": "No data generated by pipeline."}, status_code=500
            )

        safe = jsonable_encoder(result)

        # Markdown output
        if format.lower() == "md":
            report_md = safe.get("report_markdown") or "No markdown report generated."
            return PlainTextResponse(report_md)

        # Default JSON output
        return JSONResponse(content=safe, status_code=200)

    except Exception as e:
        logger.exception(f"Error running pipeline for {ticker}: {e}")
        return JSONResponse(
            content={"error": f"Pipeline failed: {str(e)}"},
            status_code=500,
        )
